jungle-royale/jungle-royale-web-server

build.gradle, src/main/java/com/example/oauthlogin/common/config/SecurityConfig.java, src/main/java/com/example/oauthlogin/common/config/SwaggerConfig.java, src/main/java/com/example/oauthlogin/common/util/JwtTokenProvider.java, src/main/java/com/example/oauthlogin/controller/LoginController.java, src/main/java/com/example/oauthlogin/controller/UserController.java, src/main/resources/application.yml
SpringDoc, Swagger 이용하여 API 자동화 명세서 연동
#8
=> feat: API Swagger 연동

.github/workflows/main.yml
=> 배포 자동화 git actions 스크립트 추가

src/main/java/com/example/jungleroyal/domain/RefreshToken.java, src/main/java/com/example/jungleroyal/service/UserServiceImpl.java, src/main/resources/application.yml
=> feat: db 컬럼 수정으로 인한 코드 수정

src/main/java/com/example/jungleroyal/common/util/AuthKakaoTokenGenerator.java, src/main/java/com/example/jungleroyal/controller/HomeController.java, src/main/resources/application-dev.yml, src/main/resources/application-prod.yml
=> 카카오 로그인 uri 변경

src/main/resources/application-prod.yml
=> feat: kakao clientid 변경

src/main/java/com/example/jungleroyal/controller/GameRoomController.java
=> feat: 방 생성 시 게임 서버 통신 수정

src/main/java/com/example/jungleroyal/common/config/WebSocketConfig.java, src/main/java/com/example/jungleroyal/common/config/WebSocketStompBrokerConfig.java, src/main/java/com/example/jungleroyal/common/handler/ChatWebSocketHandler.java, src/main/java/com/example/jungleroyal/controller/ChatController.java, src/main/java/com/example/jungleroyal/domain/dto/ChatMessageDto.java
=> feat: stomp를 이용한 채팅 서버 구현

src/main/java/com/example/jungleroyal/common/exceptions/BlacklistTokenException.java, src/main/java/com/example/jungleroyal/common/exceptions/TokenExpiredException.java, src/main/java/com/example/jungleroyal/common/handler/GlobalExceptionHandler.java, src/main/java/com/example/jungleroyal/common/types/AuthType.java, src/main/java/com/example/jungleroyal/common/util/AuthKakaoTokenUtils.java, src/main/java/com/example/jungleroyal/common/util/TimeUtils.java, src/main/java/com/example/jungleroyal/controller/AuthController.java, src/main/java/com/example/jungleroyal/controller/LogoutController.java, src/main/java/com/example/jungleroyal/controller/ManagerLogoutController.java, src/main/java/com/example/jungleroyal/domain/auth/KakaoLoginResponse.java, src/main/java/com/example/jungleroyal/domain/auth/LogoutRequest.java, src/main/java/com/example/jungleroyal/domain/dto/AuthTokensDto.java, src/main/java/com/example/jungleroyal/domain/dto/JwtTokenUserInfoDto.java, src/main/java/com/example/jungleroyal/infrastructure/AuthRefreshTokenJpaEntity.java, src/main/java/com/example/jungleroyal/infrastructure/AuthRefreshTokenJpaRepository.java, src/main/java/com/example/jungleroyal/infrastructure/AuthRefreshTokenRepositoryImpl.java, src/main/java/com/example/jungleroyal/service/JwtService.java, src/main/java/com/example/jungleroyal/service/KakaoAuthService.java, src/main/java/com/example/jungleroyal/service/UserService.java, src/main/java/com/example/jungleroyal/service/repository/AuthRefreshTokenRepositoty.java, src/main/resources/application-dev.yml
- 로그아웃시 카카오 서버에 요청
- 리프레쉬 토큰 - 엑세스토큰, 리프레시토큰 Db 저장
=> feat: 카카오 로그인 관련 로직 리팩터링

src/main/java/com/example/jungleroyal/common/config/SecurityConfig.java, src/main/java/com/example/jungleroyal/common/util/JwtAuthenticationFilter.java
=> feat: ingame 시 jwt 검증 작업 수정

src/main/java/com/example/jungleroyal/common/util/JwtAuthenticationFilter.java, src/main/resources/application-dev.yml, src/main/resources/application.yml
jwt 우회 경로 추가
-  카카오 로그인 api
- jwt 재발급 api
=> Fix 카카오 로그인 

src/main/java/com/example/jungleroyal/JungleroyalApplication.java, src/main/java/com/example/jungleroyal/common/scheduler/RoomScheduler.java, src/main/java/com/example/jungleroyal/infrastructure/GameRoomJpaRepository.java, src/main/java/com/example/jungleroyal/infrastructure/GameRoomRepositoryImpl.java, src/main/java/com/example/jungleroyal/service/GameService.java, src/main/java/com/example/jungleroyal/service/repository/GameRoomRepository.java
#144
- 게임 서버에서 방을 나가서 zero 유저가 되어도 방을 삭제하지 않고, 일정 시간동안 사람이 들어올 수 있도록 했기 때문에, leave 한 후 유저가 0명이 되어도 바로 방을 삭제하지 않도록 처리
=> fix: 유저 0명이어도 방 삭제 X

src/main/java/com/example/jungleroyal/common/config/SecurityConfig.java, src/main/resources/application.yml
=> feat: jwt 검증 우회경로 추가

src/main/java/com/example/jungleroyal/common/util/JwtAuthenticationFilter.java, src/main/java/com/example/jungleroyal/controller/GameController.java, src/main/java/com/example/jungleroyal/controller/GameRoomController.java, src/main/java/com/example/jungleroyal/domain/gameroom/GameRoomListWithUserReponse.java, src/main/java/com/example/jungleroyal/domain/user/UserInfoUsingRoomListResponse.java
게임룸 리스트 조회시 유저의 상태에 따라 방생성 or 되돌아가기 버튼 노출
=> feat: 룸리스트 조회시 유저 상태 전달 

src/main/java/com/example/jungleroyal/controller/GameController.java, src/main/java/com/example/jungleroyal/domain/gameroom/GameRoomJoinReponse.java, src/main/java/com/example/jungleroyal/service/GameRoomService.java, src/main/resources/application-dev.yml
게임 중인 유저가 직접 접속 중이 아닌 방을 선택하여 입장을 요청할 때 입장 제한을 둠
현재 유저의 gameUrl이 입장하고자 하는 방의 Url과 같으면 입장 허가
=> feat: 게임 중인 유저 다른 방 진입시 제한 로직 구현

src/main/java/com/example/jungleroyal/controller/GameRoomController.java
=> fix: 방 생성시 roomId 전송

src/main/java/com/example/jungleroyal/common/config/WebSocketStompBrokerConfig.java, src/main/resources/application-dev.yml, src/main/resources/application-prod.yml
=> feat: 웹소켓 url 연결 환경 분기처리

src/main/java/com/example/jungleroyal/controller/GameController.java, src/main/java/com/example/jungleroyal/service/GameRoomService.java
=> fix: continue 버튼 동작 안되는 버그 수정

src/main/java/com/example/jungleroyal/controller/GameRoomController.java, src/main/java/com/example/jungleroyal/domain/user/UserInfoUsingRoomListResponse.java, src/main/java/com/example/jungleroyal/infrastructure/UserRepositoryImpl.java, src/main/java/com/example/jungleroyal/service/UserService.java, src/main/java/com/example/jungleroyal/service/repository/UserRepository.java, src/main/resources/application-prod.yml
=> feat: 랭킹 시스템 구현, 배포 채팅서버 연결

src/main/java/com/example/jungleroyal/controller/GameController.java, src/main/java/com/example/jungleroyal/domain/game/GameReturnResponse.java, src/main/java/com/example/jungleroyal/service/GameRoomService.java
=> feat: continue 오류 수정

src/main/java/com/example/jungleroyal/service/GameService.java
=> feat: url 변경
